const DNO = {
  10: "Eastern England",
  11: "East Midlands",
  12: "London",
  13: "Merseyside & North Wales",
  14: "West Midlands",
  15: "North Eastern England",
  16: "North Western England",
  17: "Northern Scotland",
  18: "Southern Scotland",
  19: "South Eastern England",
  20: "Southern England",
  21: "Southern Wales",
  22: "South Western England",
  23: "Yorkshire",
  24: "Independent Power Networks",
  25: "ESP Electricity",
  26: "Last Mile Electricity",
  27: "The Electricity Network Company",
  28: "UK Power Networks (IDNO) Ltd",
  29: "Harlaxton (IDNO)",
  30: "Leep Electricity Networks (IDNO)",
  31: "Leep Electricity Networks (IDNO)",
  32: "Energy Assets Networks Ltd",
  33: "Eclipse Power Networks Ltd",
  34: "Murphy Power",
  35: "Fulcrum Electricity Assets Ltd",
  36: "Vattenfall Network Limited",
};

export default DNO;
